---
- name: Ensure NFS utilities are installed.
  package: name=nfs-utils state=present

- name: Ensure RPC services are running as configured.
  service:
    name: "{{ item }}"
    state: "{{ nfs_rpc_services_state }}"
    enabled: "{{ nfs_rpc_services_enabled }}"
  loop: "{{ nfs_rpc_services }}"
